ALTER TABLE public.quotes
  ADD COLUMN IF NOT EXISTS invoice_number TEXT,
  ADD COLUMN IF NOT EXISTS invoice_date DATE,
  ADD COLUMN IF NOT EXISTS due_date DATE,
  ADD COLUMN IF NOT EXISTS currency TEXT DEFAULT 'PHP',
  ADD COLUMN IF NOT EXISTS subtotal_php NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tax_rate NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS tax_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS discount_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS total_amount NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS payment_terms TEXT,
  ADD COLUMN IF NOT EXISTS notes_customer TEXT,
  ADD COLUMN IF NOT EXISTS notes_internal TEXT,
  ADD COLUMN IF NOT EXISTS pdf_url TEXT,
  ADD COLUMN IF NOT EXISTS sent_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_sent_date TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS payment_cash_enabled BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS payment_gcash_enabled BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS payment_gcash_number TEXT,
  ADD COLUMN IF NOT EXISTS payment_qr_enabled BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS payment_qr_url TEXT,
  ADD COLUMN IF NOT EXISTS payment_bank_enabled BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS payment_bank_name TEXT,
  ADD COLUMN IF NOT EXISTS payment_bank_account_name TEXT,
  ADD COLUMN IF NOT EXISTS payment_bank_account_number TEXT;

CREATE UNIQUE INDEX IF NOT EXISTS quotes_invoice_number_unique
  ON public.quotes (invoice_number)
  WHERE invoice_number IS NOT NULL;